<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>OpenAI 开发者论坛 - 最新帖子</title>
    <link>https://community.openai.com</link>
    <description>最新帖子</description>
    <lastBuildDate>Sat, 20 Apr 2024 03:20:14 GMT</lastBuildDate>
    <item>
      <title>看来官方推荐的java-lib库不再维护了</title>
      <link>https://community.openai.com/t/it-appears-that-the-officially-recommended-java-lib-library-is-no-longer-being-maintained/716140#post_8</link>
      <description><![CDATA[Langchain4j 是否支持 Assistants V2？还是仍在支持过程中？ &lt;img alt=&quot;:slightly_smiling_face:&quot; class=&quot;emoji&quot; height=&quot;20&quot; src=&quot;https://emoji.discourse-cdn.com/twitter/slightly_smiling_face.png?v=12&quot; title=&quot;:slightly_smiling_face: “宽度=“20”/&gt;]]></description>
      <guid>https://community.openai.com/t/it-appears-that-the-officially-recommended-java-lib-library-is-no-longer-being-maintained/716140#post_8</guid>
      <pubDate>Sat, 20 Apr 2024 03:18:33 GMT</pubDate>
    </item>
    <item>
      <title>嗯...似乎出了问题 - 错误</title>
      <link>https://community.openai.com/t/hmm-something-seems-to-have-gone-wrong-error/721937#post_9</link>
      <description><![CDATA[但问题是，为什么我们在支付这项服务费用时会做一些花招呢？]]></description>
      <guid>https://community.openai.com/t/hmm-something-seems-to-have-gone-wrong-error/721937#post_9</guid>
      <pubDate>Sat, 20 Apr 2024 03:13:57 GMT</pubDate>
    </item>
    <item>
      <title>LaPrompt 中的 200+ DALL-E 3 提示</title>
      <link>https://community.openai.com/t/200-dall-e-3-prompts-in-laprompt/603521#post_3</link>
      <description><![CDATA[谢谢先生的分享。我真的很感激！]]></description>
      <guid>https://community.openai.com/t/200-dall-e-3-prompts-in-laprompt/603521#post_3</guid>
      <pubDate>Sat, 20 Apr 2024 03:09:19 GMT</pubDate>
    </item>
    <item>
      <title>从文件搜索中检索信息的问题，Playground 与从文件搜索中检索信息的问题API使用</title>
      <link>https://community.openai.com/t/problem-of-retrieving-information-from-file-search-playground-vs-api-usage/722245#post_7</link>
      <description><![CDATA[好吧，我们使用的是python版本openai==1.2.3，所以这个版本调用了v1助手版本，最近开始检索失败。我更新到最新版本以使用 v2 助手版本 openai==1.23.2 现在它可以工作 ]]></description>
      <guid>https://community.openai.com/t/problem-of-retrieving-information-from-file-search-playground-vs-api-usage/722245#post_7</guid>
      <pubDate>Sat, 20 Apr 2024 03:03:33 GMT</pubDate>
    </item>
    <item>
      <title>帐户被盗。有人访问了我的帐户</title>
      <link>https://community.openai.com/t/account-got-hacked-someone-got-accessed-to-my-account/722444#post_8</link>
      <description><![CDATA[


 Rhap4boy：
&lt;块引用&gt;
使用成本和活动均显示零支出和零 API 请求。


您为您的组织命名了吗？这个名字现在消失了吗？
您添加了付款方式吗？现在是否没有记录付款方式，却显示“添加付款方式”？
您的帐户组织可能已被接管并移至新所有者，如前所述。这可能会让你留下一个空的。
去年年中，OpenAI 自动为很久以前创建的旧帐户添加了一个名为“个人”的额外组织，这可能是因为如果主要组织留给新所有者，该帐户之前就会变得毫无用处。
OpenAI 可以看到电荷从何而来。
您可以找出入侵的来源，并查看该访问是否仍然保留，例如安装黑客的 ChatGPT 浏览器扩展和伪造的 SORA.exe 后门。]]></description>
      <guid>https://community.openai.com/t/account-got-hacked-someone-got-accessed-to-my-account/722444#post_8</guid>
      <pubDate>Sat, 20 Apr 2024 03:00:25 GMT</pubDate>
    </item>
    <item>
      <title>关于矢量存储的一些问题</title>
      <link>https://community.openai.com/t/some-questions-about-the-vector-store/722858#post_1</link>
      <description><![CDATA[ 现在，您最多可以将一个矢量存储附加到助手，并且最多可以将一个矢量存储附加到线程。
这是否意味着助手可以同时使用两个向量数据库，一个用于线程，另一个用于自身？]]></description>
      <guid>https://community.openai.com/t/some-questions-about-the-vector-store/722858#post_1</guid>
      <pubDate>Sat, 20 Apr 2024 02:41:40 GMT</pubDate>
    </item>
    <item>
      <title>帐户被盗。有人访问了我的帐户</title>
      <link>https://community.openai.com/t/account-got-hacked-someone-got-accessed-to-my-account/722444#post_7</link>
      <description><![CDATA[在常规的 chatpgpt https://chat.openai.com 中，我看到两篇简体中文帖子我没有提示。
查看账单历史记录，它是空的。它显示“显示过去 12 个月内的发票，未找到发票”
使用成本和活动均显示零支出和零 API 请求。
ChatGPT 仍在 Plus 中，这是正确的。
我上周才开始使用 API。我记得看到过一些使用量。
谢谢。]]></description>
      <guid>https://community.openai.com/t/account-got-hacked-someone-got-accessed-to-my-account/722444#post_7</guid>
      <pubDate>Sat, 20 Apr 2024 02:39:00 GMT</pubDate>
    </item>
    <item>
      <title>“嗯……似乎出了点问题”错误</title>
      <link>https://community.openai.com/t/hmm-something-seems-to-have-gone-wrong-error/721221?page=2#post_40</link>
      <description><![CDATA[根据 OpenAI 工程师的说法，这个问题现在应该已经修复了 ]]></description>
      <guid>https://community.openai.com/t/hmm-something-seems-to-have-gone-wrong-error/721221?page=2#post_40</guid>
      <pubDate>Sat, 20 Apr 2024 02:33:51 GMT</pubDate>
    </item>
    </channel>
</rss>